---
- hosts: gcp_load_balanced_backend
  become: true

  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Copy index page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/html/index.html"

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
