apiVersion: v1
kind: Pod
metadata:
  name: myafk-pod
spec:
  containers:
    - name: test-container
      image: quay.io/myafk/interactive:stable
      command: [ "interactive", "config", "-t=fourth", "GRIDU_SECRET_ENV", "$(GRIDU_SECRET_ENV)" ]
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
          ephemeral-storage: 128M
      volumeMounts:
        - name: secret
          mountPath: /mnt/
  volumes:
    - name: secret
      secret:
        secretName: env-secret
  restartPolicy: Never
