apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  serviceName: "myservice"

---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  # Headless Service property
  clusterIP: "None"
  ports:
  - port: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: myservice
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: quay.io/myafk/interactive:stable
        command: ["interactive", "workloads", "-t=first"]
        env:
          - name: serviceName
            valueFrom:
              configMapKeyRef:
                key: serviceName
                name: env-config
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
            ephemeral-storage: "128M"
        volumeMounts:
        - name: myvolume
          mountPath: /usr/myafk
  volumeClaimTemplates:
  - metadata:
      name: myvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
