apiVersion: v1
kind: Pod
metadata:
  name: myafk-pod
spec:
  containers:
    - name: test-container
      image: quay.io/myafk/interactive:stable
      command: [ "interactive", "config", "-t=second", "GRIDU_CONFIGMAP_ENV", "$(GRIDU_CONFIGMAP_ENV)" ]
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: config
          mountPath: /mnt/
  volumes:
    - name: config
      configMap:
        name: env-config
  restartPolicy: Never
